map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

transform_tolerance: 0.5
update_frequency: 20.0
publish_frequency: 20.0
robot_radius: 0.0
inflation_radius: 0.5
cost_scaling_factor: 3.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /my_bot/laser/scan, marking: true, clearing: true}


